server:
  port: 8763

spring:
  application:
    name: eureka-server
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enabledSelfPreservation: false
    remoteRegionUrlsWithName:
      region-east: http://localhost:8761/eureka
  client:
    register-with-eureka: true
    fetch-register: true
    region: region-west
    service-url:
      zone1: http://localhost:8763/eureka
      zone2: http://localhost:8764/eureka
    availability-zones:
      region-east: zone3,zone4
    instance:
      hostname: localhost
      metadataMap.zone: zone3