###对单个指定特定名称的feign进行配置
feign:
  client:
    config:
      feignName:  ###需要配置的feignName
        ##连接超时时间
        connectTimeout: 5000
        ##读超时时间设置
        readTimeout: 5000
        ##配置Feign的日志级别
        loggerLevel: full
        ##fegin的错误解码器
        errorDecoder: com.example.ErrorDecoder
        ##配置重试
        retryer: com.example.SimpleRetryer
        ##配置拦截器
        requestInterceptors:
          - com.example.FooRequestInterceptor
          - com.example.BarRequestInterceptor
        decode404: false
        ##feign的编码器
        encoder: com.example.SimpleEncoder
        ##feign的解码器
        decoder: com.example.SimpleDecoder
        #规约定制
        contract: com.example.SimpleContract
        ###作用于所有feign
      default:
        ##连接超时时间
        connectTimeout: 5000
        ##读超时时间设置
        readTimeout: 5000
        ##配置Feign的日志级别
        loggerLevel: basic
  ###开启熔断器
  hystrix:
    enabled: true





###日志级别设置
logging:
  level:
    com.spring.Sample: debug


ribbon:
  ##请求处理超时时间
  ReadTimeout: 1200000
  ##请求连接超时时间
  ConnectTimeout: 30000


hystrix:
  #设置这个值会自动配置一个Hystrix兵法策略会把securityContext从主线程传输到你使用的Hystrix command
  shareSecurityContext: true
  command:
    ##设置所有实例的默认值
    default:
      circuitBreaker:
        ##熔断多少秒后去尝试请求
        sleepWindowInMilliseconds: 100000
        ##是否强制关闭熔断
        forceClosed: true
      execution:
        isolation:
          thread:
            ##超时时间
            timeoutInMilliseconds: 600000
